workspace(name = "example")

local_repository(
    name = "bazel_federation",
    path = "../..",
)

load("@bazel_federation//:repositories.bzl",
     "bazel_skylib",
     "bazel_skydoc"
)

bazel_skylib()
# TODO(aiuto): This is ugly. Really ugly. See //repositories.bzl for why.
# What we really need is load from within a macro to be allowed at workspace
# construction time.
load("@bazel_federation//repo_deps:bazel_skylib.bzl", "bazel_skylib_deps")
bazel_skylib_deps()

bazel_skydoc()
