workspace(name = "bazel_federation_go")

local_repository(name = "bazel_federation",
		 path = "../..",
)

load("@bazel_federation//:repositories.bzl", "io_bazel_rules_go")

io_bazel_rules_go()

load("@io_bazel_rules_go//go:def.bzl", "go_register_toolchains")

go_register_toolchains()

load("@io_bazel_rules_go//go/private:nogo.bzl", "DEFAULT_NOGO", "go_register_nogo")

go_register_nogo(name = "io_bazel_rules_nogo",
		 nogo = DEFAULT_NOGO
)
