workspace(name = "bazel_federation_go")

local_repository(
    name = "bazel_federation",
    path = "../..",
)

load("@bazel_federation//:repositories.bzl", "rules_go")

rules_go()

load("@bazel_federation//setup:rules_go.bzl", "rules_go_setup")

rules_go_setup()
