workspace(name = "bazel_federation_go")

local_repository(
    name = "bazel_federation",
    path = "../..",
)

# DO NOT SUBMIT WITH THIS
local_repository(
    name = "io_bazel_rules_go",
    path = "../../../rules_go",
)

load("@bazel_federation//:repositories.bzl", "rules_go")

rules_go()

load("@bazel_federation//setup:rules_go.bzl", "rules_go_setup")

rules_go_setup()
