workspace(name = "bazel_federation_go")

local_repository(name = "bazel_federation",
                 path = "../..",
)

load("@bazel_federation//:repositories.bzl", "io_bazel_rules_rust")

io_bazel_rules_rust()

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")
rust_repositories()

load("@io_bazel_rules_rust//:workspace.bzl", "bazel_version")
bazel_version(name = "bazel_version")
